name: Build

on:
  push:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'Realizedd/DE-ArenaRegen'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/buildtools
          key: build-${{ github.run_id }}
          restore-keys: |
            build-

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Spigot dependencies
        run: |
          [ -d ~/buildtools ] || mkdir ~/buildtools
          cd ~/buildtools
          wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.8.8
          java -jar BuildTools.jar --rev 1.12.2

      - name: Install Paper 1.8.8 dependencies
        run: |
          cd ~/buildtools
          git clone --single-branch --depth=1 --recurse-submodules -b ver/1.8.8 https://github.com/2lstudios-mc/FlamePaper.git
          pushd FlamePaper
          ./build.sh
          popd
          rm -rf FlamePaper

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Spigot dependencies
        run: |
          cd ~/buildtools
          java -jar BuildTools.jar --rev 1.14.4
          java -jar BuildTools.jar --rev 1.15.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Spigot dependencies
        run: |
          cd ~/buildtools
          java -jar BuildTools.jar --disable-java-check --rev 1.16.5
          java -jar BuildTools.jar --rev 1.17.1
          java -jar BuildTools.jar --rev 1.18.1

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v3
        with:
          name: ArenaRegen
          path: out/ArenaRegen-*.jar
